name: Checkout
on: [ push ]

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout master
      - name: List Files After
        run: ls -a
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --upgrade -r requirements.txt
      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py')
      - name: Run Mypy
        run: |
          mypy . --exclude __init__.py
      - name: Run Black Checker
        run: |
          black . --check